config/routes.rb
Rails.application.routes.draw do
root "pages#home"
get "litf" => "pages#litf"
get "contact" => "pages#contact"
get "cv" => "pages#cv"

match '/contacts',     to: 'contacts#new',             via: 'get'
resources "contacts", only: [:new, :create]

end

app/models/attachment.rb
has_attached_file :attachment,
    styles: lambda { |a| a.instance.is_image? ? {:small => "x200>", :medium => "x300>", :large => "x400>"}  : {:thumb => { :geometry => "100x100#", :format => 'jpg', :time => 10}, :medium => { :geometry => "300x300#", :format => 'jpg', :time => 10}}},
    processors: lambda { |a| a.is_video? ? [ :ffmpeg ] : [ :thumbnail ] }

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "c.ferte@hotmail.fr",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:notice] = 'Thank you for your message. We will contact you soon!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def litf
end
  def cv
end
  def contact
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<div align="center">
  <h3>Send A message to Us</h3>

  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => true %>
    <div class= "hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div>
      </br>
      <%= f.button :submit, 'Send message', :class=> "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">FERTEC</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">FERTEC</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Contact", contacts_path %></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fertec</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<div class="container">
  <%= render 'layouts/header' %>
   </div>
</head>
<style>
footer {position: fixed; bottom: 0;}
</style>
<body>

  <div class="container">
          <%= yield %>
     </div>
</body>


<footer>
  <%= render 'layouts/footer' %>
</footer>

</html>

app/views/pages/contact.html.erb
<h1>Welcome to my app!</h1>
<form method="GET" action="mailto:test@example.com" enctype="text/plain">
    <div>Subject</div>
    <input type="text" name="subject" />

    <div>Name</div>
    <input name="Name" />

    <div>E-Mail</div>
    <input name="E-Mail Address" />

    <div>Message</div>
    <textarea name="Message"></textarea>

    <br/>
    <input type="submit" value="Send" />

    <input type="hidden" name="body" />
</form>

<script>
   var form = document.getElementsByTagName('form')[0];
   form.addEventListener('submit',contact,false);
   function contact(e) {
      // Prevent Default Form Submission
      e.preventDefault();

      var target = e.target || e.srcElement;
      var i = 0;
      var message = '';

      // Loop Through All Input Fields
      for(i = 0; i < target.length; ++i) {
         // Check to make sure it's a value. Don't need to include Buttons
         if(target[i].type != 'text' && target[i].type != 'textarea') {
                // Skip to next input since this one doesn't match our rules
            continue;
         }

         // Add Input Name and value followed by a line break
         message += target[i].name + ': ' + target[i].value + "\r\n";
      }
      // Modify the hidden body input field that is required for the mailto: scheme
      target.elements["body"].value = message;

      // Submit the form since we previously stopped it. May cause recursive loop in some browsers? Should research this.
      this.submit();
   }
</script>

app/views/pages/cv.html.erb
<h1>Welcome to my app!</h1>
<p>CV</p>
<%= link_to "here", "#" %>

app/views/pages/home.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<style type="text/css">
.carousel{
    background: white;
    margin-top: 10px;
}
.carousel .item img{
    margin: left; /* Align slide image horizontally center */
}
.bs-example{
	margin: 20px;
}
img{
  float:left;
width: 425px;
height: 349px;
}
object{
  float :left;
}
</style>
<%= stylesheet_link_tag    "application", media: "all" %>
<%= javascript_include_tag "application" %>




  <div class="jumbotron">

<div class="bs-example">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Carousel indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>

        </ol>
        <!-- Wrapper for carousel items -->
        <div class="carousel-inner">
            <div class="item active">
              <h2>  <%= image_tag("fertec_logo.jpg",:size => "425x349") %> </br></br> </br>Fertec est une société de consulting, </br>  porteuse de projet inovant dans le domaine de l'industrie chimique.</h2>
            </div>


              <div class="item">
    <p>            <object width="425" height="349">
        <param name="movie" value="https://www.youtube.com/v/N83TFsZhLfU?rel=0"></param>
        <param name="allowFullScreen" value="true"></param>
        <embed src="https://www.youtube.com/v/N83TFsZhLfU?rel=0&amp;controls=0&amp;showinfo=0" type="application/x-shockwave-flash" allowfullscreen="true" width="425" height="349"></embed>

</object> </br></br>   VISION D'ENTREPRISE </br></br> L'équipe vous presente ça version de l'industrie de demain. </br></br>Ce que nous pouvont faire pour l'industrie </br>et ce que l'industrie nous aportera.</br></br></br>
 <%= link_to "nous contacter", contacts_path %> </p>
              </div>

        </div>
        <!-- Carousel controls -->

        <a class="carousel-control right" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
        </a>
    </div>
</div>
  <!-- <%= video_tag "vid.mp4", :size => "320x240", :controls => true %> -->
</div>

app/views/pages/litf.html.erb
<div class="jumbotron">
  <H1>FERTEC</H1>

  <H2>lit fluidisé</H2>

  <div class="photo_produit"> <%= image_tag("space2.jpg",:size => "425x349") %> </div>
  <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut nunc posuere, lacinia enim id, lobortis mi. Sed nec nulla arcu.  Proin pulvinar tincidunt dolor, in cursus enim aliquam nec. Sed luctus, magna vel gravida auctor, est tellus laoreet ligula, et malesuada arcu lorem et tortor. Maecenas id enim faucibus,  id viverra orci sodales vitae. Nam dolor elit, vestibulum placerat quam quis, rhoncus consectetur purus. Phasellus hendrerit hendrerit turpis.</p>
  <div class="video_produit">
    <object width="425" height="349">
      <param name="movie" value="https://www.youtube.com/v/N83TFsZhLfU?rel=0"></param>
      <param name="allowFullScreen" value="true"></param>
      <embed src="https://www.youtube.com/v/N83TFsZhLfU?rel=0&amp;controls=0&amp;showinfo=0" type="application/x-shockwave-flash" allowfullscreen="true" width="425" height="349"></embed>
    </object>
  </div>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ut nunc posuere, lacinia enim id, lobortis mi. Sed nec nulla arcu.  Proin pulvinar tincidunt dolor, in cursus enim aliquam nec. Sed luctus, magna vel gravida auctor, est tellus laoreet ligula, et malesuada arcu lorem et tortor. Maecenas id enim faucibus,  id viverra orci sodales vitae. Nam dolor elit, vestibulum placerat quam quis, rhoncus consectetur purus. Phasellus hendrerit hendrerit turpis.</p>
</div>
<div class="end">
  test
</div>